stages:
  - build
  - release
  - deploy
  - clean
  
build:
  stage: build
  tags: 
    - shell
  except:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH} .
    
release:
  stage: release
  tags: 
    - shell
  only:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION) .

deploy:
  stage: deploy
  tags:
    - shell
  except:
    - tags
  script:
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}

deploy-release:
  stage: deploy
  tags:
    - shell
  only:
    - tags
  script:
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)
    
clean-build:
  stage: clean
  tags:
    - shell
  except:
    - tags
  script:
    - docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}

clean-release:
  stage: clean
  tags:
    - shell
  only:
    - tags
  script:
    - docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)
