stages:
  - build
  - deploy
  - clean
  
build:
  stage: build
  tags: 
    - shell
  except:
    - tags
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH} .
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}
    
release:
  stage: deploy
  tags: 
    - shell
  only:
    - tags
    - master
  script:
    - docker build --pull --force-rm=true --tag=$(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION) .
    - docker push $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)

clean-build:
  stage: clean
  tags:
    - shell
  except:
    - tags
  script:
    - docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}

clean-release:
  stage: clean
  tags:
    - shell
  only:
    - tags
  script:
    - docker rmi $(cat REPOSITORY)/${CI_PROJECT_PATH}:$(cat VERSION)
