version: '2'
services:
  redis-master:
    container_name: redis-master
    restart: always
    image: datacore/alpine-redis:latest
    hostname: master
    ports:
      - 6379:6379
    environment:
      - REDIS=1
      - REDIS_PASSWORD=password
      - SLAVE_IP=<IP>
      - SLAVE_PORT=6379
