version: '2'
services:
  redis-master-sentinel:
    container_name: redis-master-sentinel
    restart: always
    image: datacore/docker-alpine-redis:latest
    hostname: master-sentinel
    ports:
      - 6379:6379
      - 26379:26379
    environment:
      - REDIS=1
      - REDIS_PASSWORD=password
      - SLAVE_IP=<IP>
      - SLAVE_PORT=6379
      - SENTINEL=1
      - SENTINEL_IP=<IP>
      - SENTINEL_PORT=26379
      - SENTINEL_MSET=rmaster
      - SENTINEL_MHOST=<IP>
      - SENTINEL_MPASS=password
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER_MS=15000
      - SENTINEL_FAILOVER_TIMEOUT=30000